fixtures:
  symlinks:
    bsd: "#{source_dir}"

  repositories:
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: '1.2.5'
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '4.4.0'
    sysctl:
      repo: 'git://github.com/duritong/puppet-sysctl'
      ref: '0.0.5'
  forge_modules:
    shell_config: 'csail/shell_config'

