fixtures:
  symlinks:
    my_module: "#{source_dir}"

  repositories:
    sysctl: 'git://github.com/duritong/puppet-sysctl'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat'
  forge_modules:
    shell_config: 'csail/shell_config'

